CREATE TABLE jh203518.PROJECT(
    Manager INT NOT NULL CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY(Manager) REFERENCES jh203518.EMPLOYEE(Id),
    Completion VARCHAR(100),
    Topic VARCHAR(100) NOT NULL,
    Cost FLOAT NOT NULL
)