CREATE TABLE jh203518.RUNS(
    EmployeeId INT NOT NULL FOREIGN KEY(EmployeeId) REFERENCES jh203518.EMPLOYEE(Id),
    DepartmentId INT NOT NULL FOREIGN KEY(DepartmentId) REFERENCES jh203518.DEPARTMENT(Id),
)