CREATE TABLE jh203518.TRUCK(
    StoreId INT NOT NULL FOREIGN KEY(StoreId) REFERENCES jh203518.STORE(Id),
    EmployeeId INT NOT NULL FOREIGN KEY(EmployeeId) REFERENCES jh203518.EMPLOYEE(Id),
    Efficiency VARCHAR(100),
    Cost FLOAT NOT NULL
)