CREATE TABLE jh203518.WEBSITE(
    URL VARCHAR(256) CONSTRAINT PK_RESTRICTION_URL PRIMARY KEY,
    DailyVisitors INT NOT NULL,
    Manager INT NOT NULL CONSTRAINT FK_WEBSITE_MANAGER FOREIGN KEY(Manager) REFERENCES jh203518.EMPLOYEE(Id),
);