SELECT * FROM UNIVERSITY.ATTRACTIONHISTORY;
INSERT INTO UNIVERSITY.ATTRACTIONHISTORY
VALUES ('Big Thunder Mountain Railroad', '2024-05-01', 'It rained');

SELECT * FROM UNIVERSITY.ATTRACTIONHISTORY 
WHERE AttractionName = 'Haunted Mansion';

DELETE FROM UNIVERSITY.ATTRACTIONHISTORY WHERE AttractionName = 'Haunted Mansion' AND HistoryDate = '2024-05-01';
